name: Build and Deploy
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Node
        uses: actions/setup-node@v2
        with:
          node-version: '22.6.0'

      - name: Install
        run: |
          npm install
          npm run build:client

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/client
          branch: gh-pages
